version: '3.8'

services:
  # MariaDB数据库
  mariadb:
    image: m.daocloud.io/docker.io/library/mariadb:10.11
    container_name: linguaforge-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: linguaforge_root_password
      MYSQL_DATABASE: linguaforge
      MYSQL_USER: linguaforge
      MYSQL_PASSWORD: linguaforge_password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - linguaforge-network

  # Redis缓存
  redis:
    image: m.daocloud.io/docker.io/library/redis:7-alpine
    container_name: linguaforge-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - linguaforge-network

  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: linguaforge-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ENVIRONMENT: production
      PORT: 8080
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: linguaforge
      DB_PASSWORD: linguaforge_password
      DB_NAME: linguaforge
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRE_HOURS: 24
    depends_on:
      - mariadb
      - redis
    networks:
      - linguaforge-network

  # 前端构建服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: linguaforge-frontend
    restart: unless-stopped
    volumes:
      - frontend_dist:/app/dist
    networks:
      - linguaforge-network

  # Nginx反向代理
  nginx:
    image: m.daocloud.io/docker.io/library/nginx:alpine
    container_name: linguaforge-nginx
    restart: unless-stopped
    ports:
      - "3000:80"
      - "3443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - linguaforge-network

volumes:
  mariadb_data:
  redis_data:
  frontend_dist:

networks:
  linguaforge-network:
    driver: bridge
